-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE 'DISPATCHED';

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "parcelHeight" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "parcelLength" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "parcelWeight" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "parcelWidth" DECIMAL(65,30) NOT NULL DEFAULT 0;
